server:
  port: 10000

#JDBC
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@//localhost:1521/XE
#    username: hr
#    password: 1234

# mybatis
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/XE
      username: hr
      password: 1234
  ssl:
    enabled: true
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:3000"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
api :
  base-url : "https://apis.data.go.kr/B551011/KorPetTourService"
  area-based-list : "/areaBasedList"
  service-key : "ifySbrAfQ6xzLynwNtMTRIyjNfECuZkN3y%2F3345uKqcXyU3jN4dbK6nv2oxAhIuBTIj5PY7%2FskSuI6u3%2BfdG3A%3D%3D"


thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"